version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  node: circleci/node@5.2.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  react-native: {}

filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  command-test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - react-native/yarn_install

workflows:
  test-deploy:
    jobs:
      - command-test:
          filters: *filters

      - node/run:
          yarn-run: semantic-release
          version: "20.11"
          pkg-manager: yarn
          requires:
            - command-test
          filters:
            branches:
              only: main

      - orb-tools/pack:
          filters: *release-filters

      - orb-tools/publish:
          orb_name: react-native-community/react-native
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-test
          context: orb-publishing
          filters: *release-filters
